---


- hosts: localhost
  remote_user: root
  become: yes

  tasks:
    - name: Ubuntu automatic security updates
      copy:
        src=20auto-upgrades
        dest=/etc/apt/apt.conf.d/20auto-upgrades

    - name: Install unattended-upgrades
      apt:
        pkg=unattended-upgrades
        state=latest
        update_cache=yes

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest

    - name: Copy scripts
      copy:
        src: "{{ item }}"
        dest: /tmp/
        owner: root
        group: root
        mode: 0777
      with_items:
        - script1.sh
        - script2.sh
        - script3.sh

    - name: Install mastodon packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - nginx
        - imagemagick
        - ffmpeg
        - libpq-dev
        - libxml2-dev
        - libxslt1-dev
        - file
        - git-core
        - g++
        - libprotobuf-dev
        - protobuf-compiler
        - pkg-config
        - gcc
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm3
        - libgdbm-dev
        - redis-server
        - redis-tools
        - postgresql
        - postgresql-contrib
        - postgresql-client-common
        - postgresql-client
        - libidn11-dev
        - libicu-dev
        - language-pack-en

    - name: Copy nginx conf
      copy:
        src: mastodon.com.conf
        dest: /etc/nginx/sites-available/mastodon.com.conf
        owner: root
        group: root
        mode: 0777

    - name: Activate nginx conf
      command: ln -s ../sites-available/mastodon.com.conf
      args:
        chdir: /etc/nginx/sites-enabled/
        creates: /etc/nginx/sites-enabled/mastodon.com.conf

    - name: Copy systemd sevices files
      copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/{{ item }}
      with_items:
        - mastodon-sidekiq.service
        - mastodon-streaming.service
        - mastodon-web.service

    - name: Enable systemd services
      command: systemctl enable /etc/systemd/system/mastodon-{{ item }}
      with_items:
        - mastodon-sidekiq.service
        - mastodon-streaming.service
        - mastodon-web.service



