---
- name: Install mastodon packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - imagemagick
    - ffmpeg
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - file
    - git-core
    - g++
    - libprotobuf-dev
    - protobuf-compiler
    - pkg-config
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - redis-server
    - redis-tools
    - postgresql
    - postgresql-contrib
    - postgresql-client-common
    - postgresql-client
    - libidn11-dev
    - libicu-dev
    - language-pack-en
